# Train test split

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df_walmart = pd.read_csv("walmart_ventas.csv")
df_walmart.head(10)

   id_compra objeto_vendido  cantidad  precio
0          1         Laptop         5  724.00
1          2   Pasta dental         2    2.36
2          3        Manzana         7    0.46
3          4            Pan         4    2.26
4          5   Pasta dental         1    2.50
5          6        Manzana         9    0.47
6          7        Zapatos        10   47.20
7          8         Champú         1    8.50
8          9          Jeans         6   46.78
9         10         Champú         6    7.45

In [3]:
X = df_walmart.drop(columns=["precio"])

y = df_walmart["precio"]

In [4]:
print(f"La cantidad de elementos de es {X.shape}")
X.head()

La cantidad de elementos de es (10000, 3)

   id_compra objeto_vendido  cantidad
0          1         Laptop         5
1          2   Pasta dental         2
2          3        Manzana         7
3          4            Pan         4
4          5   Pasta dental         1

In [5]:
print(f"La cantidad de elementos de es {y.shape}")
y.head()

La cantidad de elementos de es (10000,)

0    724.00
1      2.36
2      0.46
3      2.26
4      2.50
Name: precio, dtype: float64

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=11,test_size=0.2)

In [7]:
print(f"La cantidad de elementos de es {X_train.shape}")
X_train.head()

La cantidad de elementos de es (8000, 3)

      id_compra objeto_vendido  cantidad
4199       4200        Naranja        10
757         758         Champú         2
4001       4002         Laptop         2
8163       8164         Laptop         7
4250       4251          Leche         7

In [8]:
print(f"La cantidad de elementos de es {X_test.shape}")
X_test.head()

La cantidad de elementos de es (2000, 3)

      id_compra objeto_vendido  cantidad
3104       3105             TV         8
6353       6354       Camiseta         4
8689       8690       Teléfono        10
5857       5858          Jeans         6
6011       6012     Calcetines         8

In [9]:
print(f"La cantidad de elementos de es {y_train.shape}")
y_train.head()

La cantidad de elementos de es (8000,)

4199      0.58
757       7.50
4001    834.60
8163    815.04
4250      3.49
Name: precio, dtype: float64

In [10]:
print(f"La cantidad de elementos de es {y_test.shape}")
y_test.head()

La cantidad de elementos de es (2000,)

3104    495.19
6353     19.07
8689    626.23
5857     45.39
6011      5.46
Name: precio, dtype: float64